# Generated by Django 4.1.3 on 2023-07-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModernMarket_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_image',
            field=models.ImageField(upload_to='static/product_images/'),
        ),
    ]
