# Generated by Django 4.1.3 on 2023-07-06 12:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ModernMarket_home', '0005_alter_cart_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=datetime.datetime(2023, 7, 6, 12, 49, 29, 793073, tzinfo=datetime.timezone.utc))),
                ('phoneNum', models.CharField(default='+911234567890', max_length=15)),
                ('email', models.EmailField(default='johndoe@email.com', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('addr1', models.CharField(max_length=200)),
                ('fname', models.CharField(default='John', max_length=100)),
                ('lname', models.CharField(default='Doe', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModernMarket_home.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
