# Generated by Django 4.1.3 on 2023-07-06 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModernMarket_home', '0006_order_delete_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_ratecount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 23, 22, 3, 261971, tzinfo=datetime.timezone.utc)),
        ),
    ]
