# Generated by Django 4.1.3 on 2023-07-06 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModernMarket_home', '0008_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 23, 22, 33, 946256, tzinfo=datetime.timezone.utc)),
        ),
    ]
