# Generated by Django 4.1.3 on 2023-07-06 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModernMarket_home', '0009_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rated',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 23, 41, 34, 693558, tzinfo=datetime.timezone.utc)),
        ),
    ]
