# Generated by Django 4.1.3 on 2023-07-06 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModernMarket_home', '0010_order_rated_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 23, 54, 59, 83233, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='rated',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=7),
        ),
    ]
