# Generated by Django 4.1.3 on 2023-07-07 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModernMarket_home', '0015_alter_order_order_date_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 10, 2, 31, 296767, tzinfo=datetime.timezone.utc)),
        ),
    ]
