# Generated by Django 4.1.2 on 2023-07-12 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ModernMarket_home", "0016_alter_order_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 12, 18, 3, 3, 487310, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
