# Generated by Django 4.1.2 on 2023-07-14 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ModernMarket_home", "0017_alter_order_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 14, 13, 34, 22, 170936, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
